# Generated by Django 4.0.3 on 2022-03-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='NOME', max_length=30)),
                ('rg', models.CharField(db_column='RG', max_length=9)),
                ('cpf', models.CharField(db_column='CPF', max_length=11)),
                ('data_nascimento', models.DateField(db_column='DATA_NASCIMENTO')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_curso', models.CharField(db_column='CODIGO_CURSO', max_length=10)),
                ('descricao', models.CharField(db_column='DESCRICAO', max_length=100)),
                ('nivel', models.CharField(choices=[('B', 'Básico'), ('I', 'Intermediário'), ('A', 'Avançado')], db_column='NIVEL', default='B', max_length=1)),
            ],
        ),
    ]
